name: Feature Request
description: Suggest a new feature or improvement
title: "[feat]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature, we appreciate your creativity and effort! Please fill out the information below to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see added.
      placeholder: "e.g. I'd like to push a button in settings and ... happens"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        e.g., "I often need to... but currently Valkyr doesn't support..."
        or "It would be helpful if Valkyr could..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe your ideal solution. Consider the following:
        - What would the UX be like?
        - What would the expected outcome be?
        - How should it integrate with existing features?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        e.g., "I currently work around this by..."
        or "My devleopment workflow is to ... but I need to ..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other context, screenshots, or examples that would help us understand your request.
