import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ExternalLink } from 'lucide-react';
import { Button } from '../ui/button';
import { Checkbox } from '../ui/checkbox';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '../ui/dialog';
import { SlugInput } from '../ui/slug-input';
import { Label } from '../ui/label';
import { Separator } from '../ui/separator';
import { MultiAgentDropdown } from '../agents/MultiAgentDropdown';
import { type Agent } from '../../types';
import { type AgentRun } from '../../types/chat';
import { agentMeta } from '../../providers/meta';
import { isValidProviderId, getProvider } from '@shared/providers/registry';
import type { ProviderId } from '@shared/providers/registry';
import { getSettings } from '../../services/settingsService';
import {
  generateFriendlyTaskName,
  normalizeTaskName,
  MAX_TASK_NAME_LENGTH,
} from '../../lib/taskNames';
import BranchSelect, { type BranchOption } from '../git/BranchSelect';

const DEFAULT_AGENT: Agent = 'claude';

interface SubRepo {
  path: string;
  name: string;
  relativePath: string;
  gitInfo: {
    isGitRepo: boolean;
    remote?: string;
    branch?: string;
    baseRef?: string;
  };
}

interface TaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  onCreateTask: (
    name: string,
    initialPrompt?: string,
    agentRuns?: AgentRun[],
    autoApprove?: boolean,
    useWorktree?: boolean,
    baseRef?: string,
    selectedSubRepos?: string[]
  ) => void;
  projectName: string;
  defaultBranch: string;
  existingNames?: string[];
  projectPath?: string;
  branchOptions?: BranchOption[];
  isLoadingBranches?: boolean;
  subRepos?: SubRepo[] | null;
  hasExistingNonWorktreeTask?: boolean;
}

const TaskModal: React.FC<TaskModalProps> = ({
  isOpen,
  onClose,
  onCreateTask,
  projectName,
  defaultBranch,
  existingNames = [],
  projectPath,
  branchOptions = [],
  isLoadingBranches = false,
  subRepos,
  hasExistingNonWorktreeTask = false,
}) => {
  // Form state
  const [taskName, setTaskName] = useState('');
  const [agentRuns, setAgentRuns] = useState<AgentRun[]>([{ agent: DEFAULT_AGENT, runs: 1 }]);
  const [error, setError] = useState<string | null>(null);
  const [touched, setTouched] = useState(false);
  const [isFocused, setIsFocused] = useState(false);
  const [autoApprove, setAutoApprove] = useState(false);
  const [useWorktree, setUseWorktree] = useState(true);
  const [chatMode, setChatMode] = useState<'acp' | 'pty'>('acp');

  // Multi-repo selection state - initialized with all repos selected
  const [selectedSubRepos, setSelectedSubRepos] = useState<string[]>([]);

  // Sync selectedSubRepos when subRepos changes or modal opens
  useEffect(() => {
    if (isOpen && subRepos && subRepos.length > 0) {
      setSelectedSubRepos(subRepos.map((r) => r.relativePath));
    }
  }, [isOpen, subRepos]);

  // Branch selection state - sync with defaultBranch unless user manually changed it
  const [selectedBranch, setSelectedBranch] = useState(defaultBranch);
  const userChangedBranchRef = useRef(false);
  const taskNameInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isOpen && !userChangedBranchRef.current) {
      setSelectedBranch(defaultBranch);
    }
  }, [isOpen, defaultBranch]);

  const handleBranchChange = (value: string) => {
    setSelectedBranch(value);
    userChangedBranchRef.current = true;
  };

  // Auto-name tracking
  const [autoGeneratedName, setAutoGeneratedName] = useState('');
  const userHasTypedRef = useRef(false);
  const autoNameInitializedRef = useRef(false);
  const customNameTrackedRef = useRef(false);

  // Computed values
  const activeAgents = useMemo(() => agentRuns.map((ar) => ar.agent), [agentRuns]);
  const hasAutoApproveSupport = activeAgents.every((id) => !!agentMeta[id]?.autoApproveFlag);
  const primaryAgent = agentRuns[0]?.agent || DEFAULT_AGENT;
  const primaryProviderDef = useMemo(() => getProvider(primaryAgent as ProviderId), [primaryAgent]);
  const hasAcpSupport = !!primaryProviderDef?.acpSupport;

  const normalizedExisting = useMemo(
    () => existingNames.map((n) => normalizeTaskName(n)).filter(Boolean),
    [existingNames]
  );

  // Validation
  const validate = useCallback(
    (value: string): string | null => {
      const normalized = normalizeTaskName(value);
      if (!normalized) return 'Please enter a session name.';
      if (normalizedExisting.includes(normalized))
        return 'A session with this name already exists.';
      if (normalized.length > MAX_TASK_NAME_LENGTH)
        return `Session name is too long (max ${MAX_TASK_NAME_LENGTH} characters).`;
      return null;
    },
    [normalizedExisting]
  );

  // Clear auto-approve if not supported
  useEffect(() => {
    if (!hasAutoApproveSupport && autoApprove) setAutoApprove(false);
  }, [hasAutoApproveSupport, autoApprove]);

  // Reset mode when agent changes
  useEffect(() => {
    if (!hasAcpSupport) {
      setChatMode('pty');
    }
  }, [hasAcpSupport]);

  // Reset form and load settings when modal opens
  useEffect(() => {
    if (!isOpen) return;

    // Reset state
    setTaskName('');
    setAutoGeneratedName('');
    setError(null);
    setTouched(false);
    setIsFocused(false);
    setAutoApprove(false);
    setUseWorktree(true);
    setChatMode('acp');
    userHasTypedRef.current = false;
    autoNameInitializedRef.current = false;
    customNameTrackedRef.current = false;
    userChangedBranchRef.current = false;
    setSelectedBranch(defaultBranch);

    // Generate initial name
    const suggested = generateFriendlyTaskName(normalizedExisting);
    setAutoGeneratedName(suggested);
    setTaskName(suggested);
    setError(validate(suggested));
    autoNameInitializedRef.current = true;

    // Load settings
    let cancel = false;
    getSettings().then((settings) => {
      if (cancel) return;

      const settingsAgent = settings?.defaultProvider;
      const agent: Agent = isValidProviderId(settingsAgent)
        ? (settingsAgent as Agent)
        : DEFAULT_AGENT;
      setAgentRuns([{ agent, runs: 1 }]);

      const autoApproveByDefault = settings?.tasks?.autoApproveByDefault ?? false;
      setAutoApprove(autoApproveByDefault && !!agentMeta[agent]?.autoApproveFlag);

      // Set default chat mode from provider overrides
      const providerDef = getProvider(agent as ProviderId);
      if (!providerDef?.acpSupport) {
        setChatMode('pty');
      } else if (settings?.providerOverrides) {
        const override = settings.providerOverrides[agent];
        setChatMode(override?.defaultChatMode === 'cli' ? 'pty' : 'acp');
      }

      // Handle auto-generate setting
      if (settings?.tasks?.autoGenerateName === false && !userHasTypedRef.current) {
        setAutoGeneratedName('');
        setTaskName('');
        setError(null);
      }
    });

    return () => {
      cancel = true;
    };
  }, [isOpen]);

  const handleNameChange = (val: string) => {
    setTaskName(val);
    setError(validate(val));
    userHasTypedRef.current = true;

    // Track custom naming for telemetry (only once per session)
    if (
      autoGeneratedName &&
      val !== autoGeneratedName &&
      val.trim() &&
      !customNameTrackedRef.current
    ) {
      customNameTrackedRef.current = true;
      void (async () => {
        const { captureTelemetry } = await import('../../lib/telemetryClient');
        captureTelemetry('task_custom_named', { custom_name: 'true' });
      })();
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setTouched(true);

    const err = validate(taskName);
    if (err) {
      setError(err);
      return;
    }

    // Close modal immediately - task creation happens in background
    // The task will appear in sidebar via optimistic UI update
    onClose();

    // Fire and forget - don't await
    try {
      onCreateTask(
        normalizeTaskName(taskName),
        undefined,
        agentRuns,
        hasAutoApproveSupport ? autoApprove : false,
        useWorktree,
        selectedBranch,
        subRepos && subRepos.length > 0 ? selectedSubRepos : undefined
      );
    } catch (error) {
      console.error('Failed to create task:', error);
    }
  };

  const handleOpenAutoFocus = useCallback((event: Event) => {
    event.preventDefault();
    taskNameInputRef.current?.focus({ preventScroll: true });
  }, []);

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent
        className="max-h-[calc(100vh-48px)] max-w-md overflow-visible"
        onOpenAutoFocus={handleOpenAutoFocus}
      >
        <DialogHeader>
          <DialogTitle>New Session</DialogTitle>
          <div className="space-y-1 pt-1">
            <p className="text-foreground text-sm font-medium">{projectName}</p>
            <div className="flex items-center gap-1.5">
              <span className="text-muted-foreground text-xs">from</span>
              {branchOptions.length > 0 ? (
                <BranchSelect
                  value={selectedBranch}
                  onValueChange={handleBranchChange}
                  options={branchOptions}
                  isLoading={isLoadingBranches}
                  variant="ghost"
                />
              ) : (
                <span className="text-muted-foreground text-xs">
                  {isLoadingBranches ? 'Loading...' : selectedBranch || defaultBranch}
                </span>
              )}
            </div>
          </div>
        </DialogHeader>

        <Separator />

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <Label htmlFor="task-name" className="mb-2 block">
              Session name
            </Label>
            <SlugInput
              ref={taskNameInputRef}
              id="task-name"
              value={taskName}
              onChange={handleNameChange}
              onFocus={() => setIsFocused(true)}
              onBlur={() => {
                setTouched(true);
                setIsFocused(false);
              }}
              placeholder="refactor-api-routes"
              maxLength={MAX_TASK_NAME_LENGTH}
              className={`w-full ${touched && error && !isFocused ? 'border-destructive focus-visible:border-destructive focus-visible:ring-destructive' : ''}`}
              aria-invalid={touched && !!error && !isFocused}
            />
          </div>

          <div className="flex items-center gap-4">
            <Label className="shrink-0">Agent</Label>
            <MultiAgentDropdown agentRuns={agentRuns} onChange={setAgentRuns} />
          </div>

          {hasAcpSupport && (
            <div className="flex items-center gap-4">
              <Label className="shrink-0">Mode</Label>
              <div className="flex rounded-md border p-0.5">
                <button
                  type="button"
                  className={`px-3 py-1 text-xs font-medium transition-colors ${
                    chatMode === 'acp'
                      ? 'bg-primary text-primary-foreground rounded-none'
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                  onClick={() => setChatMode('acp')}
                >
                  ACP
                </button>
                <button
                  type="button"
                  className={`px-3 py-1 text-xs font-medium transition-colors ${
                    chatMode === 'pty'
                      ? 'bg-primary text-primary-foreground rounded-none'
                      : 'text-muted-foreground hover:text-foreground'
                  }`}
                  onClick={() => setChatMode('pty')}
                >
                  CLI
                </button>
              </div>
              <span className="text-muted-foreground text-[10px]">
                {chatMode === 'acp' ? 'Structured chat UI' : 'Raw terminal'}
              </span>
            </div>
          )}

          <div className="flex items-center gap-4">
            <Label className="shrink-0">Worktree</Label>
            <label
              className={`inline-flex items-start gap-2 text-sm leading-tight ${hasExistingNonWorktreeTask ? 'cursor-not-allowed' : 'cursor-pointer'}`}
            >
              <Checkbox
                checked={useWorktree || hasExistingNonWorktreeTask}
                onCheckedChange={(checked) => {
                  if (hasExistingNonWorktreeTask) return;
                  setUseWorktree(checked === true);
                }}
                disabled={hasExistingNonWorktreeTask}
                className="mt-[1px]"
              />
              <div className="space-y-0.5">
                <span className="text-muted-foreground text-xs">
                  {useWorktree || hasExistingNonWorktreeTask
                    ? 'Isolated Git worktree'
                    : 'Work on current branch'}
                </span>
                {hasExistingNonWorktreeTask && (
                  <p className="text-muted-foreground text-[10px]">
                    Required: another session uses the project directory
                  </p>
                )}
                {!useWorktree && !hasExistingNonWorktreeTask && (
                  <p className="text-destructive text-[10px]">
                    Changes will affect your working directory
                  </p>
                )}
              </div>
            </label>
          </div>

          {/* Multi-repo selection */}
          {subRepos && subRepos.length > 0 && (
            <div className="flex items-start gap-4">
              <Label className="shrink-0 pt-1">Repositories</Label>
              <div className="min-w-0 flex-1 space-y-2">
                <p className="text-muted-foreground text-xs">
                  {useWorktree
                    ? 'Select repos for worktrees. Others will be symlinked.'
                    : 'Select repos to track changes for.'}
                </p>
                <div className="space-y-1">
                  {subRepos.map((repo) => (
                    <label
                      key={repo.relativePath}
                      className="flex cursor-pointer items-center gap-2 text-sm"
                    >
                      <Checkbox
                        checked={selectedSubRepos.includes(repo.relativePath)}
                        onCheckedChange={(checked) => {
                          if (checked) {
                            setSelectedSubRepos([...selectedSubRepos, repo.relativePath]);
                          } else {
                            setSelectedSubRepos(
                              selectedSubRepos.filter((p) => p !== repo.relativePath)
                            );
                          }
                        }}
                      />
                      <span className="font-mono text-xs">{repo.name}</span>
                      {repo.gitInfo.branch && (
                        <span className="text-muted-foreground text-xs">
                          ({repo.gitInfo.branch})
                        </span>
                      )}
                    </label>
                  ))}
                </div>
              </div>
            </div>
          )}

          {hasAutoApproveSupport && (
            <div className="flex items-center gap-4">
              <Label className="shrink-0">Auto-approve</Label>
              <label className="inline-flex cursor-pointer items-start gap-2 text-sm leading-tight">
                <Checkbox
                  checked={autoApprove}
                  onCheckedChange={(checked) => setAutoApprove(checked === true)}
                  className="mt-[1px]"
                />
                <div className="space-y-0.5">
                  <span className="text-muted-foreground text-xs">
                    Skip permissions for file ops
                  </span>
                  <a
                    href="https://simonwillison.net/2025/Oct/22/living-dangerously-with-claude/"
                    target="_blank"
                    rel="noreferrer noopener"
                    className="text-foreground ml-1 inline-flex items-center gap-1 text-[10px] underline"
                  >
                    Learn more
                    <ExternalLink className="h-3 w-3" aria-hidden="true" />
                  </a>
                </div>
              </label>
            </div>
          )}

          <DialogFooter>
            <Button type="submit" disabled={!!validate(taskName)}>
              Create
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default TaskModal;
